global:
  resolve_timeout: 2m
route:
  receiver: "PrometheusAlert"
  group_by: [...]
  routes:
    - receiver: "webhook1"
      group_interval: 10s
      group_wait: 30s
      group_by: [nodeExt1]
      repeat_interval: 2m
      match:
        team: backend_b
        type: service_status
    - receiver: "webhook1"
      group_interval: 10s
      group_wait: 30s
      group_by: [nodeExt2]
      repeat_interval: 2m
      match:
        team: backend_b
        type: service_status
receivers:
  - name: 'PrometheusAlert'
    webhook_configs:
      - url: 'http://prometheus-alert.infwaves.com/prometheusalert?type=fs&tpl=prometheus-fs'
  - name: "webhook1"
    webhook_configs:
      - url: "http://prometheus-alert.infwaves.com/prometheusalert?type=fs&tpl=prometheus-fs&fsurl=${你的飞书webhook地址}"
